### ISSUE TITLE
How to save an image from a buffer in RGB Color Type ?

### ISSUE THREAD

**Issue by Tantatorn-dev** [strawlab/pylon-cxx#4]
Hello. I've followed [the example of grabbing images](https://github.com/strawlab/pylon-cxx/blob/main/examples/grab.rs). I grabbed an image and saved a buffer to a file with image::save_buffer. The buffer size is 2,304,000 and this image has a resolution 1920*1200. I'm able to save it in Grayscale Color Mode (image::ColorType::L8). But I can't save it with image::ColorType::RGB8. 

This is a function I used for saving an image.
By the way, I've tried capture an image manually via PylonViewer and read that image and convert it to &[u8]. I see that its size is 6,912,000 that is the triple of buffer size I grabbed. 
Are there anyway I can solve this problem ? 

```
fn save_image(bytes: &[u8]) -> Result<(), ()> {
    image::save_buffer("out.jpg", bytes, 1920, 1200, image::ColorType::RGB8);
    Ok(())
}
```

This is a stack trace error I got when I tried to save a buffer to a file.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/codecs/jpeg/encoder.rs:456:97
stack backtrace:
   0:       0x557a269058 - std::backtrace_rs::backtrace::libunwind::trace::hecc4fb3dc5a91037
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:       0x557a269058 - std::backtrace_rs::backtrace::trace_unsynchronized::h9f238248263b1f81
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:       0x557a269058 - std::sys_common::backtrace::_print_fmt::hae64a821d41b4b14
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:       0x557a269058 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha504e6c6649c19e9
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:       0x557a283584 - core::fmt::write::h7c914d42a8e99f57
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:       0x557a267180 - std::io::Write::write_fmt::hb2f3ddc6101ed08d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:       0x557a26ab4c - std::sys_common::backtrace::_print::h1e31b5a4bc5a5719
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:       0x557a26ab4c - std::sys_common::backtrace::print::h3453f1f2e887cb14
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:       0x557a26ab4c - std::panicking::default_hook::{{closure}}::hd0cacc29652b13c4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:       0x557a26a664 - std::panicking::default_hook::h0d7faf1abbe91b0d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:       0x557a26b1a4 - std::panicking::rust_panic_with_hook::he3ac366c10fca72f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:       0x557a26acb0 - std::panicking::begin_panic_handler::{{closure}}::h1a8dd2d97f4ecde7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:       0x557a269518 - std::sys_common::backtrace::__rust_end_short_backtrace::hace36748d5046612
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:       0x557a26ac44 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:       0x557a192be8 - core::panicking::panic_fmt::h202c536f80469a06
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:       0x557a192b6c - core::panicking::panic::h1bdc9a224d23727e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:       0x557a1b22b4 - core::option::Option<T>::unwrap::hd48a12989d1cdaeb
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:388:21
  17:       0x557a1c2dcc - image::codecs::jpeg::encoder::JpegEncoder<W>::encode::h1774014df8f54cfb
                               at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/codecs/jpeg/encoder.rs:456:53
  18:       0x557a1cee24 - <image::codecs::jpeg::encoder::JpegEncoder<W> as image::image::ImageEncoder>::write_image::h3aea4ffe85efff17
                               at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/codecs/jpeg/encoder.rs:685:9
  19:       0x557a1a5290 - image::io::free_functions::save_buffer_with_format_impl::hb90c947950e75c24
                               at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/io/free_functions.rs:172:37
  20:       0x557a1a4bf4 - image::io::free_functions::save_buffer_impl::h526102c179635595
                               at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/io/free_functions.rs:151:5
  21:       0x557a1937ec - image::dynimage::save_buffer::h14c42aeb4e46841e
                               at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/dynimage.rs:1269:5
  22:       0x557a194530 - try_basler_camera::save_image::hffa7246905a78be6
                               at /home/dev/Desktop/try-basler-camera/src/main.rs:60:5
  23:       0x557a19436c - try_basler_camera::main::hafde5e3bfd048e68
                               at /home/dev/Desktop/try-basler-camera/src/main.rs:46:13
  24:       0x557a193344 - core::ops::function::FnOnce::call_once::ha727d60b0ece1ae2
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  25:       0x557a1935f4 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha437209cc032f6f5
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  26:       0x557a193680 - std::rt::lang_start::{{closure}}::h7fd8159998d960e5
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:49:18
  27:       0x557a26b560 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a5ad580efb8d75c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  28:       0x557a26b560 - std::panicking::try::do_call::hf30891cd5c1e383c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  29:       0x557a26b560 - std::panicking::try::ha129bc0854027027
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  30:       0x557a26b560 - std::panic::catch_unwind::h7c8483f4e19ba89c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  31:       0x557a26b560 - std::rt::lang_start_internal::he67f78edad2eefd1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  32:       0x557a193658 - std::rt::lang_start::h24547122cd9ef037
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:48:5
  33:       0x557a194578 - main
  34:       0x7f82d56720 - __libc_start_main
  35:       0x557a1931f0 - <unknown>
```

**Comment by astraw** [comment]
I just updated the grab example to:

- show how to set the pixel format
- report the pixel format
- not to (potentially falsely) claim the pixel value was a gray value

The buffer is the raw buffer directly from the Pylon driver and thus in whatever pixel format came from the camera. I think this should address your issue.

**Comment by Tantatorn-dev** [comment]
That works. Thanks a lot. 😄
